# Generated by Django 5.0 on 2024-04-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='attachments',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='doc',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
